Metrics/BlockLength:
  Exclude:
    - 'hets-rabbitmq-wrapper.gemspec'
    - 'spec/**/*'
    - 'db/migrate/*'

Style/AlignParameters:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
