hets:
  path:

agent:
  id: 1

backend:
  api_key: FqeNBVtaNi3D5Bdsgk6_DDCbMqATpsEYxBtx3iZmsfb7y21rHqEXYnXRb3AasEZY

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  virtual_host: ontohub_development

sneakers:
  # The number of parallel worker processes.
  workers: 1
