hets:
  path: /usr/bin/false

agent:
  id: 4711

backend:
  api_key: test_api_key

rabbitmq:
  host: '::1'
  port: 25672
  username: tester
  password: testing
  prefix: hets_agent_test
  exchange: hets_agent_test
